version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: musicapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: musicuser
      POSTGRES_PASSWORD: musicpass
      POSTGRES_DB: musicapp
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
